---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build the lib with Idris2 HEAD
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ilex
        run: pack typecheck ilex
      - name: Build examples
        run: pack --no-prompt typecheck ilex-examples
      - name: Test ilex
        run: pack --no-prompt test ilex
      - name: Run profiler
        run: pack --no-prompt run ilex-profile
      - name: Build ilex-json
        run: pack typecheck ilex-json
      - name: Test ilex-json
        run: pack --no-prompt test ilex-json
